CREATE DATABASE aula02_05; 
CREATE TABLE tb_vendas(
    ID_NF INT,
    ID_ITEM INT,
    COD_PROD VARCHAR(10),
    VALOR_UNIT DECIMAL(10,2),
    QUANTIDADE INT,
    DESCONTO DECIMAL(10,2)
);

INSERT INTO tb_vendas (ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, QUANTIDADE, DESCONTO) VALUES
(1, 1, '1', 25, 10, 5),
(1, 2, '1', 13.50, 3, null),
(1, 3, '2', 15, 2, null),
(1, 4, '3', 10, 1, null),
(1, 5, '4', 30, 1, null),
(2, 1, '3', 15, 4, null),
(2, 2, '4', 10, 5, null),
(2, 3, '5', 30, 7, null),
(3, 1, '1', 25, 2, null),
(3, 2, '4', 10, 4, null),
(3, 3, '5', 30, 5, null),
(3, 4, '2', 13.50, 7, null),
(4, 1, '5', 30, 10, 15),
(4, 2, '4', 10, 12, 5),
(4, 3, '1', 25, 13, 5),
(4, 4, '2', 13.50, 15, 5),
(5, 1, '3', 15, 3, null),
(5, 2, '5', 30, 6, null),
(6, 1, '1', 25, 22, 15),
(6, 2, '3', 15, 25, 20),
(7, 1, '1', 25, 10, 3),
(7, 2, '2', 13.50, 10, 4),
(7, 3, '3', 15, 10, 4),
(7, 4, '5', 30, 10, 1); 


-- A

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT  
FROM tb_vendas
WHERE DESCONTO IS NULL;

-- B
SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, VALOR_UNIT - (VALOR_UNIT * (DESCONTO/100)) AS 'VALOR_VENDIDO'
FROM tb_vendas;

-- C

UPDATE tb_vendas SET DESCONTO = 0 
WHERE DESCONTO = NULL;


-- D

SELECT ID_NF, ID_ITEM, COD_PROD, VALOR_UNIT, (QUANTIDADE * VALOR_UNIT) AS 'VALOR_TOTAL', DESCONTO, VALOR_UNIT - (VALOR_UNIT * (DESCONTO/100)) AS 'VALOR_VENDIDO'
FROM tb_vendas;

-- E

SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS 'VALOR_TOTAL'
FROM tb_vendas
GROUP BY ID_NF
ORDER BY VALOR_TOTAL DESC;

-- F

SELECT ID_NF, SUM((VALOR_UNIT) - (VALOR_UNIT * (DESCONTO / 100))) AS 'VALOR_VENDIDO'
FROM tb_vendas
GROUP BY ID_NF 
ORDER BY VALOR_VENDIDO DESC;

-- G

SELECT COD_PROD, MAX(QUANTIDADE) AS 'MAX_QTDE'
FROM tb_vendas
GROUP BY COD_PROD;

-- H

SELECT ID_NF, COD_PROD, QUANTIDADE
FROM tb_vendas
GROUP BY ID_NF, COD_PROD, QUANTIDADE
HAVING QUANTIDADE > 10;

-- I

SELECT ID_NF, SUM(QUANTIDADE * VALOR_UNIT) AS 'VALOR_TOT'
FROM tb_vendas
GROUP BY ID_NF
HAVING SUM(QUANTIDADE * VALOR_UNIT) > 500
ORDER BY VALOR_TOT DESC;

-- J

SELECT COD_PROD, AVG(DESCONTO) AS 'MEDIA'
FROM tb_vendas
GROUP BY COD_PROD;

-- K
SELECT COD_PROD, MIN(DESCONTO) AS 'MENOR', MAX(DESCONTO) AS 'MAIOR', AVG(DESCONTO) AS 'MEDIA'
FROM tb_vendas
GROUP BY COD_PROD;

-- L

SELECT ID_NF, COUNT(ID_NF) AS 'QTD_ITENS'
FROM tb_vendas
GROUP BY ID_NF
HAVING COUNT(ID_NF) > 3;